# main.py
import sys
from PySide6.QtWidgets import QApplication, QMainWindow, QFileDialog
from PySide6.QtCore import Qt

# Import the generated UI class
from views.ui_main_window import Ui_MainWindow
from controllers.main_controller import MainController
from utils.image_utils import cv_img_to_pixmap


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        # Setup the UI generated by Qt Designer
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Initialize Controller
        self.controller = MainController()

        # Connect Signals
        self.ui.upload_btn.clicked.connect(self.upload_image)
        self.ui.image_label.mousePressEvent = self.label_clicked

    def label_clicked(self, event):
        """Triggered when the user clicks the dashed drop-zone."""
        self.upload_image()

    def generate_roc(self):
        # TODO
        ...


    def upload_image(self):
        file_path, _ = QFileDialog.getOpenFileName(
            self, "Open Image", "", "Image Files (*.png *.jpg *.jpeg *.bmp *.pgm)"
        )

        if file_path:
            try:
                # Ask controller to process the image
                display_img, prepared_face = self.controller.handle_image_upload(file_path)
                pixmap = cv_img_to_pixmap(display_img)
                # Update UI
                self.ui.image_label.setPixmap(pixmap.scaled(
                    self.ui.image_label.width(), self.ui.image_label.height(),
                    Qt.KeepAspectRatio, Qt.SmoothTransformation
                ))


            except Exception as e:
                print(f"Error processing image: {e}")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())